apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "example.fullname" . }}
  labels:
    app: {{ include "example.name" . }}
    chart: {{ include "example.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "example.fullname" . }}
          servicePort: 3000
