apiVersion: v1
kind: Pod
metadata:
  name: showntell
  labels:
    app: showntell
spec:
  containers:
  - name: container1
    image: tomwells/bootcamp:v1.0.10
    imagePullPolicy: Always
    ports:
    - containerPort: 3000
    resources:
      limits:
        cpu: 1000m
        memory: "1000Mi"
      requests:
        cpu: 200m
        memory: "500Mi"
